# Set the version of docker compose to use
version: "3.9"

services:
  server:
    build: .
    container_name: server
    command: npm start
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - HOST=0.0.0.0
    env_file:
      - ./.env.dev
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
  postgres:
    image: postgres:13
    restart: always
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/rewards?schema=public
    env_file:
      - ./.env.dev
